define
  menu:
    day_to_day: "Day to Day"
    reports: "Reports"
    income: "Income"
    expenses: "Expenses"
    other: "Other"
    actions: "Actions"
    building: "Building"
    tenants: "Tenant Directory"
    message_board: "Message Board"
    tasks: "Tasks"
    listings: "Listings"
    applicants: "Applicants"
    add_lease: "Add lease"
    add_tenants: "Add tenants"
    add_income: "Add income"
    add_expense: "Add expense"
    add_post: "Add a post"
    add_task: "Add a task"
    add_listing: "Advertise"
    occupancy: "Occupancy"
    incomes: "Income"
    expenses: "Expenses"
    cash_transactions: "Cash Transactions"
    lease_history: "Lease History"
    edit_property: "Edit Property"
    edit_units: "Edit Units"
    managers: "Managers"
    view_public: "See Public View"
    view_tenant: "See Tenant View"
  form:
    marketing: "Marketing"
    contact: "Contact"
    building: "Building"
    features: "Features"
    amenities: "Amenities"
  errors:
    messages:
      access_denied: "You do not have access to the property."
      missing: 'You must select a property.'